(function(c){function p(a){var b,d;b=!0==c.isArray(a.image)?a.image[Math.floor(Math.random()*a.image.length)]:a.image;d="left"==a.enter_from?"right":"left";b='<div id="kp_come_container" style="width:'+a.width+"px; height:"+a.height+"px; "+a.enter_from+":-"+a.width+'px; bottom:0;"><img src="'+b+'" style="width:'+a.width+"px; height:"+a.height+'px;"><div id="kp_popup" style="'+a.enter_from+":"+.8*a.width+"px;top:"+.28*a.height+"px;-webkit-border-radius:"+a.popup_radius+";-moz-border-radius:"+a.popup_radius+
";border-radius:"+a.popup_radius+";background-color:"+a.popup_bgcolor+'"><div id="kp_says" style="color:'+a.popup_color+'">'+a.default_text+'</div><div id="kp_popup_arrow_shadow" style="border-'+d+": 40px solid rgba(0,0,0,.1);"+a.enter_from+': -40px;"></div><div id="kp_popup_arrow" style="border-'+d+": 42px solid "+a.popup_bgcolor+";"+a.enter_from+': -40px;"></div><div id="kp_close_popup">X</div></div></div>';c("body").append(b);m(a)}function m(a){var b={},d;c.get(a.api,function(g){var e=0;c.each(g.data,
function(a,c){b[e]=c;e++});var f=b[Math.floor(Math.random()*(e-1))];link='<a href="'+f.url+'" target="_blank" class="kp_readmore" style="color:'+a.readmore_color+'">\u4e86\u89e3\u66f4\u591a\u67ef\u6587\u54f2\u7684\u653f\u898b</a>';g=f.title.replace(/\u3010\u67efp\u65b0\u653f\u3011/g,"");f=f.plain_content.replace(/\u67ef\u6587\u54f2/g,"\u6211").replace(/\u53f0\u5317\u5e02\u9577\u53c3\u9078\u4eba/g,"").replace(/\u6211\u8868\u793a/g,"\u6211\u8a8d\u70ba").replace(/\u6211\u6307\u51fa/g,"\u6211\u8a8d\u70ba").replace("\u4eca\uff0829\uff09\u65e5",
"").replace("\u300c","").replace("\u300d","").replace("\u67efP\u7684\u4e3b\u5f35\u6211\u7684\u653f\u7b56\u4e3b\u5f35","\u6211\u4e3b\u5f35");f=f.split("\n");d=void 0==f[1]?'<p id="kp_say_bighi" style="color:'+a.popup_color+'">'+a.default_text+"<br>\u6211\u63d0\u51fa<br>\u300c"+g.substring(2)+"\u300d</p>"+link:'<p id="kp_say_hi" style="color:'+a.popup_color+'">'+a.default_text+"</p>"+f[3]+f[4]+"..."+link+"</p>";c("#kp_says").scrollTop(0).html(d).promise().done(function(){c("p").removeAttr("style");
c("span").removeAttr("style")})})}function e(a){switch(a){case "fade":c("#kp_popup").fadeIn("slow");break;case "slide":c(".kp_readmore").hide(function(){c("#kp_popup").slideDown("fast",function(){c(".kp_readmore").fadeIn()})});break;case "zoom":c("#kp_says").hide(function(){c("#kp_popup").show("slow",function(){c("#kp_says").fadeIn()})});break;default:c("#kp_popup").show()}}c.kptalks=function(a){var b=c.extend({api:"http://api.kptaipei.tw/v1/category/40?accessToken=kp53f568e77303e9.28212837",image:["http://goooooooogle.github.io/kp/img/kp.png",
"http://goooooooogle.github.io/kp/img/kp-2.png"],height:450,width:466,effect:"default",popup_effect:"fade",popup_radius:"8px",popup_color:"black",popup_bgcolor:"beige",readmore_color:"brown",comein_position:80,default_text:"\u4f60\u597d\uff0c\u6211\u662f\u67ef\u6587\u54f2",enter_from:"left",enter_distance:-130},a);p(b);var d=c("#kp_come_container");a=c("#kp_come_container img");var g=c("#kp_popup"),q=c("#kp_close_popup");c(window).scroll(function(){var a=c(window).scrollTop(),k=c(window).height(),
l=c(document).height(),h={},n={};h[b.enter_from]=b.enter_distance+"px";n[b.enter_from]="-"+b.width+"px";if(a+k>b.comein_position/100*l){if(d.css(b.enter_from)=="-"+b.width+"px")switch(b.effect){case "fast":d.animate(h,100,function(){e(b.popup_effect)});break;case "slow":d.animate(h,1E3,function(){e(b.popup_effect)});break;case "veryslow":d.animate(h,1E4,function(){e(b.popup_effect)});break;case "jump":d.css("bottom","-"+b.height+"px").css(b.enter_from,b.enter_distance);d.animate({bottom:0},300).animate({bottom:"-10px"},
50).animate({bottom:0},50).animate({bottom:"-10px"},50).animate({bottom:0},300,function(){e(b.popup_effect)});break;case "sneaky":a={};k={};l={};a[b.enter_from]="-"+.54*b.width+"px";k[b.enter_from]="-"+.6*b.width+"px";l[b.enter_from]="-"+.7*b.width+"px";d.animate(a,2E3).delay(2E3).animate(k,1E3).delay(1E3).animate(a,1E3).delay(2E3).animate(l,2E3).delay(1E3).animate(h,3E3,function(){e(b.popup_effect)});break;default:d.animate(h,500,function(){e(b.popup_effect)})}}else d.css(b.enter_from)==b.enter_distance+
"px"&&(g.hide(),d.animate(n,100),m(b))});a.click(function(){var a={};a[b.enter_from]="-"+(b.width+10)+"px";g.remove();d.animate(a,100)});q.click(function(){g.hide();m(b)})}})(jQuery);
